### ISSUE TITLE
Melhorias

### ISSUE THREAD

**Issue by kyriosdata** [keslleylima/i-2018#1]
- Paths não deveriam conter espaços, nem tampouco acentos, o mesmo vale para nomes de packages em Java. Substitua. 
- O exercício 1 fala em argumento recebido pelo programa, você está usando a entrada padrão para obter o valor, ou seja, use o vetor args (nome geralmente empregado).

**Comment by kyriosdata** [comment]
- Exercicio7 não implementa o que foi requisitado.
- Exercicio8 não fornecido.
- É preciso seguir um padrão de codificação. Existe uma estrutura que beneficia todos quando é seguida. Java tem convenções. 
- É preciso documentar (Javadoc).

**Comment by keslleylima** [comment]
Realizado apontamentos levantados, sendo assim, fechando issues
