### ISSUE TITLE
Melhorias exercício 2

### ISSUE THREAD

**Issue by kyriosdata** [keslleylima/i-2018#2]
- Forneça a sua documentação em vez daquela gerada pelo seu IDE. 
- A estratégia pode ser melhorada, em particular, não há necessidade de ler todo o conteúdo do arquivo. Adicionalmente, não há garantia de que isso foi feito conforme o seu código (veja https://docs.oracle.com/javase/7/docs/api/java/io/DataInputStream.html#read(byte[]) para detalhes).

**Comment by keslleylima** [comment]
Realizado apontamentos levantados, sendo assim, fechando issues
